apiVersion: v1
kind: Service
metadata:
  labels:
    app: unitygowebapi
  name: unitygowebapi
  namespace: default
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: unitygowebapi
